name: C/ASM CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' # Важно для подключения bignum-common

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential yasm

    - name: Build project (Debug)
      run: make build CONFIG=release

    - name: Run unit tests (Debug)
      run: make test CONFIG=release

    - name: Create distribution
      run: make dist

    - name: Upload dist artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist